In [11]:
import numpy as np
import matplotlib.pyplot as plt
from algorithms import *
from gridworld import GridWorld
ALG_NAMES = ['Sarsa',
             'Q-learning',
             'Sarsa-lambda',
             'Q-lambda']

# Regular Gridworld

## Sarsa

In [24]:
env = GridWorld(stochastic_wind=False, print_board=False)
algorithm = ALG_NAMES[0]
num_episodes = 800
alpha = 0.5
epsilon = 0.1
gamma = 1
lam = 0.5

In [25]:
rl = Sarsa(env=env, alpha=alpha, epsilon=epsilon, gamma=gamma, table_init='zeros')
eps = rl.train(num_episodes)
y = []
for i, _ in enumerate(eps):
    y.append(i)
    

	Took 15 moves to reach the goal


[(array([1, 3]), 0, -1),
 (array([2, 3]), 0, -1),
 (array([3, 3]), 0, -1),
 (array([4, 4]), 0, -1),
 (array([5, 5]), 0, -1),
 (array([6, 6]), 0, -1),
 (array([7, 6]), 0, -1),
 (array([8, 6]), 0, -1),
 (array([9, 6]), 0, -1),
 (array([9, 5]), 3, -1),
 (array([9, 4]), 3, -1),
 (array([9, 3]), 3, -1),
 (array([9, 2]), 3, -1),
 (array([8, 2]), 2, -1),
 (array([7, 3]), 2, 1)]

Vary alpha

## Q-learning

## Sarsa-Lambda

## Q-Lambda

# Regular Gridworld

## Sarsa

## Q-learning

## Sarsa-Lambda

## Q-Lambda